# Default server port configuration
# Can be overridden by setting SERVER_PORT environment variable
server.port=8082
org.gradle.jvmargs=-Dpath=/usr/local/bin:/usr/bin:/bin

# Filter versions
cpAuthFilterVersion=1.0.10
cpAuditFilterVersion=1.0.5
#other versions##
apiSpecVersion=0.3.4
jobManagerVersion=1.0.9
log4JVersion=2.24.3
logbackVersion=1.5.18
lombokVersion=1.18.46
testcontainersBomVersion=1.20.4
networkntJsonSchemaVersion=1.5.1