import uk.gov.moj.cpp.authz.drools.Outcome;
import uk.gov.moj.cpp.authz.drools.Action;
import uk.gov.hmcts.cp.acl.SecurityGroupConstants;
import uk.gov.hmcts.cp.acl.PermissionConstants;

global uk.gov.moj.cpp.authz.http.providers.UserAndGroupProvider userAndGroupProvider;

rule "Allow – court-list-publish post (publish-court-list only)"
when
  $o: Outcome()
  $a: Action(name == "courtlistpublishing-service.publish.post")
  eval(userAndGroupProvider.hasPermission($a, PermissionConstants.accessToPublishCourtListPermissions()))
then
  $o.setSuccess(true);
end

rule "Allow – sjp publish (System Users only)"
when
  $o: Outcome()
  $a: Action(name == "courtlistpublishing-service.sjp.post")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, SecurityGroupConstants.getSystemUserOnlyRoles()))
then
  $o.setSuccess(true);
end

rule "Allow – court-list-publish and download"
when
  $o: Outcome()
  $a: Action(name in ("courtlistpublishing-service.publish.get",
                      "courtlistpublishing-service.files.download",
                      "courtlistpublishing-service.download.get"))
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, SecurityGroupConstants.getPublishingRoles()))
then
  $o.setSuccess(true);
end

rule "Allow – prison court-list download (Prison Admin, Listing Officers, Legal Advisers, Court Clerks, CTSC Admin, Operational Delivery Admin)"
when
  $o: Outcome()
  $a: Action(name == "courtlistpublishing-service.prison-download.get")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, SecurityGroupConstants.getPrisonListRoles()))
then
  $o.setSuccess(true);
end

rule "Allow – public-court-list"
when
  $o: Outcome()
  $a: Action(name == "courtlistpublishing-service.public-court-list.get")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, SecurityGroupConstants.getPublishingRoles()))
then
  $o.setSuccess(true);
end

rule "Allow – publish-status-cleanup (System Users only)"
when
  $o: Outcome()
  $a: Action(name == "courtlistpublishing-service.publish-status-cleanup")
  eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($a, SecurityGroupConstants.getSystemUserOnlyRoles()))
then
  $o.setSuccess(true);
end